---
title: "Funding for science. Example 1"
author: Karlis Pleiko
date: August 03, 2018
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
---

Data about 2016

LV funding: http://www.izm.gov.lv/lv/zinatne/valsts-finansejums-zinatnei

UC Davis funding: https://research.ucdavis.edu/about-us/reports-publications/annual-research-funding/

##LV data

```{r}

private <- 23.8
universities <- 3.2
state_funding <- 52.7
foreign <- 30.7
total_EUR <- private + universities + state_funding + foreign
message("This is total LV funding in 2016 (M eur):  ", total_EUR)
```

##UC Davis data

```{r}
UCDavis_USD <- 760
#USD to EUR exchange rate on July 2016
exch_rate_USD_to_EUR <- 0.903770 
UCDavis_EUR <- UCDavis_USD*exch_rate_USD_to_EUR
message("This is total funding for research at UC Davis in 2016 (M eur):  ", UCDavis_EUR)

```

##Number of students and funding

Data (students) UC Davis: https://www.ucdavis.edu/sites/default/files/upload/files/uc-davis-student-profile.pdf

Data LV (students) (page 33): http://www.izm.gov.lv/images/statistika/augst_izgl/AII_2017_parskats.pdf

GDP data 2016 (USD, 2010 PPPs): https://stats.oecd.org/index.aspx?DataSetCode=PDB_LV


```{r}
UCDavis_students <- 36441
LV_students <-84282
LV_eur_per_student <- total_EUR/LV_students*10^6
UCDavis_eur_per_student <- UCDavis_EUR/UCDavis_students*10^6

LV_eur_per_student
UCDavis_eur_per_student

percentage_per_student <- LV_eur_per_student/UCDavis_eur_per_student*100
percentage_per_student


US_GDP_per_person <- 52321
LV_GDP_per_person <- 22866

message("NOTE: Expenses per student are in eur 2016, but GDP as USD 2010 PPPs, thus it should be considered only as a indicative value")
UCDavis_perc_to_GDP <- UCDavis_eur_per_student/US_GDP_per_person*100
UCDavis_perc_to_GDP

LV_perc_to_GDP <- LV_eur_per_student/LV_GDP_per_person*100
LV_perc_to_GDP
```


##Summary

```{r}
LV_percentage <- round(total_EUR/UCDavis_EUR*100, 2)
message("This is LV total funding for science as % from UC Davis science funding in 2016:  ", LV_percentage)
```